### ISSUE TITLE
Percentage issue

### ISSUE THREAD

**Issue by sergeevabc** [coriolinus/calc#11]
Dear Peter,
I am trying to calculate as follows
```console
$ calc.exe 130-20%
Error: unexpected EOF
130-20%              
       ^             
```
However other CLI calculators such as [Qalc][1] output 104 as expected.

[1]: https://github.com/Qalculate/libqalculate/releases/

**Comment by coriolinus** [comment]
Thank you for your error report. Percentages are not currently a supported feature of `calc`. Here are some supported ways to perform that calculation:

```
$ calc '130 * 0.8'
104
$ calc '130 * (1 - .2)'
104
```

**Comment by coriolinus** [comment]
Please use the tools which support your use cases! This feature request was closed because I am not going to find the time to implement it in the foreseeable future. I will review a PR if you open one though.
