### ISSUE TITLE
Hex value being assigned as f64 by default

### ISSUE THREAD

**Issue by EricB-ADI** [coriolinus/calc#18]
I am running the example using hex

```bash
[0]: 0xab :b 4
operation `0x...` not implemented for f64
```
It seems the option parser is incorrectly assigning the hex value.

**Comment by coriolinus** [comment]
Unfortunately the internal data type is set at launch time and can only be updated by rerunning the program. Use the `-i` flag when you launch to use a `i64` as the data type, or `-u` to use a `u64`. When using either of those data types, your expression evaluates properly.

```shell
$ calc -i
[0]: 0xab :b 4
1010 1011
$ calc -u
[0]: 0xab :b 4
1010 1011
```
